# MacOSSandboxing.cmake
# macOS Sandboxing Configuration for OpenVisionKit
# Prepares applications for App Store distribution with sandboxing
# **Feature: macos-build-support, Property 15: Security configuration compliance**
# **Validates: Requirements 8.5**

include(CMakeParseArguments)

# ============================================================================
# Sandboxing Configuration Options
# ============================================================================

option(MACOS_ENABLE_SANDBOXING "Enable App Sandbox for macOS builds" OFF)
option(MACOS_SANDBOX_NETWORK_CLIENT "Allow outbound network connections" OFF)
option(MACOS_SANDBOX_NETWORK_SERVER "Allow incoming network connections" OFF)
option(MACOS_SANDBOX_CAMERA "Allow camera access in sandbox" ON)
option(MACOS_SANDBOX_MICROPHONE "Allow microphone access in sandbox" ON)
option(MACOS_SANDBOX_USB "Allow USB device access in sandbox" OFF)
option(MACOS_SANDBOX_PRINT "Allow printing in sandbox" OFF)
option(MACOS_SANDBOX_BLUETOOTH "Allow Bluetooth access in sandbox" OFF)

# File access options
option(MACOS_SANDBOX_USER_SELECTED_FILES "Allow access to user-selected files" ON)
option(MACOS_SANDBOX_DOWNLOADS_READ "Allow read access to Downloads folder" OFF)
option(MACOS_SANDBOX_DOWNLOADS_WRITE "Allow write access to Downloads folder" OFF)
option(MACOS_SANDBOX_PICTURES_READ "Allow read access to Pictures folder" OFF)
option(MACOS_SANDBOX_PICTURES_WRITE "Allow write access to Pictures folder" OFF)
option(MACOS_SANDBOX_MOVIES_READ "Allow read access to Movies folder" ON)
option(MACOS_SANDBOX_MOVIES_WRITE "Allow write access to Movies folder" ON)

# ============================================================================
# Sandboxing Functions
# ============================================================================

# Function to generate sandbox entitlements
function(generate_sandbox_entitlements OUTPUT_FILE)
    if(NOT APPLE)
        return()
    endif()
    
    set(ENTITLEMENTS_CONTENT "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<!--
    OpenVisionKit Sandbox Entitlements
    Generated by CMake for App Store distribution
-->
<plist version=\"1.0\">
<dict>
    <!-- Enable App Sandbox -->
    <key>com.apple.security.app-sandbox</key>
    <true/>
")
    
    # Network entitlements
    if(MACOS_SANDBOX_NETWORK_CLIENT)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Allow outbound network connections -->
    <key>com.apple.security.network.client</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_NETWORK_SERVER)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Allow incoming network connections -->
    <key>com.apple.security.network.server</key>
    <true/>
")
    endif()
    
    # Hardware entitlements
    if(MACOS_SANDBOX_CAMERA)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Camera access for video capture -->
    <key>com.apple.security.device.camera</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_MICROPHONE)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Microphone access for audio capture -->
    <key>com.apple.security.device.audio-input</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_USB)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- USB device access -->
    <key>com.apple.security.device.usb</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_PRINT)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Printing access -->
    <key>com.apple.security.print</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_BLUETOOTH)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Bluetooth access -->
    <key>com.apple.security.device.bluetooth</key>
    <true/>
")
    endif()
    
    # File access entitlements
    if(MACOS_SANDBOX_USER_SELECTED_FILES)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Read-write access to user-selected files -->
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_DOWNLOADS_READ)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Read access to Downloads folder -->
    <key>com.apple.security.files.downloads.read-only</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_DOWNLOADS_WRITE)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Read-write access to Downloads folder -->
    <key>com.apple.security.files.downloads.read-write</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_PICTURES_READ)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Read access to Pictures folder -->
    <key>com.apple.security.assets.pictures.read-only</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_PICTURES_WRITE)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Read-write access to Pictures folder -->
    <key>com.apple.security.assets.pictures.read-write</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_MOVIES_READ)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Read access to Movies folder -->
    <key>com.apple.security.assets.movies.read-only</key>
    <true/>
")
    endif()
    
    if(MACOS_SANDBOX_MOVIES_WRITE)
        string(APPEND ENTITLEMENTS_CONTENT "
    <!-- Read-write access to Movies folder -->
    <key>com.apple.security.assets.movies.read-write</key>
    <true/>
")
    endif()
    
    # Required entitlements for video processing
    string(APPEND ENTITLEMENTS_CONTENT "
    <!-- JIT compilation for OpenCV optimizations -->
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    
    <!-- Unsigned executable memory for OpenCL kernels -->
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    
    <!-- Disable library validation for third-party libraries -->
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
</dict>
</plist>")
    
    file(WRITE "${OUTPUT_FILE}" "${ENTITLEMENTS_CONTENT}")
    message(STATUS "Generated sandbox entitlements: ${OUTPUT_FILE}")
endfunction()

# Function to configure sandboxing for a target
function(configure_sandbox TARGET_NAME)
    if(NOT APPLE)
        return()
    endif()
    
    if(NOT MACOS_ENABLE_SANDBOXING)
        return()
    endif()
    
    cmake_parse_arguments(SANDBOX
        ""
        "ENTITLEMENTS_FILE"
        ""
        ${ARGN}
    )
    
    # Generate entitlements file if not provided
    if(NOT SANDBOX_ENTITLEMENTS_FILE)
        set(SANDBOX_ENTITLEMENTS_FILE "${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}.sandbox.entitlements")
        generate_sandbox_entitlements("${SANDBOX_ENTITLEMENTS_FILE}")
    endif()
    
    # Configure Xcode attributes for sandboxing
    set_target_properties(${TARGET_NAME} PROPERTIES
        XCODE_ATTRIBUTE_CODE_SIGN_ENTITLEMENTS "${SANDBOX_ENTITLEMENTS_FILE}"
        XCODE_ATTRIBUTE_ENABLE_APP_SANDBOX YES
    )
    
    message(STATUS "  Sandboxing configured for ${TARGET_NAME}")
endfunction()

# Function to validate sandbox configuration
function(validate_sandbox_configuration)
    if(NOT APPLE)
        return()
    endif()
    
    if(NOT MACOS_ENABLE_SANDBOXING)
        return()
    endif()
    
    set(SANDBOX_WARNINGS "")
    
    # Check for potentially problematic configurations
    if(NOT MACOS_SANDBOX_USER_SELECTED_FILES)
        list(APPEND SANDBOX_WARNINGS "User-selected file access is disabled - users won't be able to open files")
    endif()
    
    if(NOT MACOS_SANDBOX_CAMERA AND NOT MACOS_SANDBOX_MOVIES_READ)
        list(APPEND SANDBOX_WARNINGS "Neither camera nor movie folder access is enabled - video input may be limited")
    endif()
    
    # Report warnings
    foreach(WARNING ${SANDBOX_WARNINGS})
        message(WARNING "Sandbox: ${WARNING}")
    endforeach()
    
    # Report sandbox configuration
    message(STATUS "macOS Sandbox Configuration:")
    message(STATUS "  Sandboxing: ${MACOS_ENABLE_SANDBOXING}")
    message(STATUS "  Network Client: ${MACOS_SANDBOX_NETWORK_CLIENT}")
    message(STATUS "  Network Server: ${MACOS_SANDBOX_NETWORK_SERVER}")
    message(STATUS "  Camera: ${MACOS_SANDBOX_CAMERA}")
    message(STATUS "  Microphone: ${MACOS_SANDBOX_MICROPHONE}")
    message(STATUS "  User-Selected Files: ${MACOS_SANDBOX_USER_SELECTED_FILES}")
    message(STATUS "  Movies Read: ${MACOS_SANDBOX_MOVIES_READ}")
    message(STATUS "  Movies Write: ${MACOS_SANDBOX_MOVIES_WRITE}")
endfunction()

# ============================================================================
# Security-Scoped Bookmarks Support
# ============================================================================

# Function to add security-scoped bookmark support to a target
function(add_security_scoped_bookmark_support TARGET_NAME)
    if(NOT APPLE)
        return()
    endif()
    
    # Add compile definition for security-scoped bookmark support
    target_compile_definitions(${TARGET_NAME} PRIVATE
        MACOS_SECURITY_SCOPED_BOOKMARKS=1
    )
    
    message(STATUS "  Security-scoped bookmark support added for ${TARGET_NAME}")
endfunction()

# ============================================================================
# Initialization
# ============================================================================

# Validate sandbox configuration when this module is included
if(APPLE AND MACOS_ENABLE_SANDBOXING)
    validate_sandbox_configuration()
endif()
